---
- name: start and enable opensm
  service: name=opensm state=started enabled=yes
  tags: [infiniband-ringmember, services]

- name: install quagga
  yum: name=quagga state=installed
  tags: [infiniband-ringmember, packages]

- name: quagga config for ospf
  template: src={{ item }} dest=/etc/quagga/ owner=quagga group=quaggavt
  with_items:
    - zebra.conf
    - ospfd.conf
  tags: [infiniband-ringmember, configs]
  notify: restart quagga

- name: start and enabled quagga ospf
  service: name={{ item }} state=started enabled=yes
  with_items:
    - zebra
    - ospfd
  tags: [infiniband-ringmember, services]
