---
- name: run interface templates
  template: src={{ item }} dest=/etc/sysconfig/network-scripts
  with_items:
    - ifcfg-ib0
    - ifcfg-ib1
  tags: [infiniband-ringmember, configs]

# this is a different technique for getting the port GUIDS
# for the opensm template
#- name: get ib port guids
#  shell: ibstat -p | paste -sd " "
#  register: ibports
#  ignore_errors: True
#  always_run: True
#  tags: [infiniband-ringmember, configs]

- name: run opensm sysconfig template
  template: src=opensm dest=/etc/sysconfig/opensm
  tags: [infiniband-ringmember, configs]
  notify: restart opensm