---
- hosts: labcluster
  roles:
    - base-centos6
    - hypervisor
    - infiniband-host
    - infiniband-ringmember
    - glusterfs-server
    - glusterfs-client
    - {role: clusternode, cluster_group: labcluster, apcpdu_group: apcpdus}
  vars:
    ntp: #see ntp.conf in the base-centos6 role for details
      servers:
        - 0.centos.pool.ntp.org
        - 1.centos.pool.ntp.org
        - 2.centos.pool.ntp.org
    ssmtp: #see ssmtp.conf in the base-centos6 role for details
      mailhub: mx.google.com
      RewriteDomain: example.com
    vnetworks:
      - {name: Border, vlan: 10}
      - {name: Core, vlan: 11}
      - {name: Service, vlan: 12}
      - {name: Inf, vlan: 13}
      - {name: Client, vlan: 14}
      - {name: Guest, vlan: 15}
      - {name: vWS, vlan: 16}
      - {name: BMI, vlan: 20}
      - {name: OOBM, vlan: 21}
      - {name: Imaging, vlan: 33}
    ccs_config_version: 1
    vmfds:
      - {name: hyper121p, nodes:[hyper121, hyper122, hyper123]}
      - {name: hyper122p, nodes:[hyper122, hyper123, hyper121]}
      - {name: hyper123p, nodes:[hyper123, hyper121, hyper122]}
    vms: []
