---
- hosts: lab
  roles:
    - base-centos6
    - hypervisor
  vars:
    ssmtp: #see ssmtp.conf for details
      mailhub: mx.google.com
      RewriteDomain: example.com
    ntp:
      servers:
        - 0.centos.pool.ntp.org
        - 1.centos.pool.ntp.org
        - 2.centos.pool.ntp.org