---
- include: iptables.yml
- meta: flush_handlers
- include: sshsetup.yml
- include: hostsfile.yml

- name: ensure hypervisor services are disabled
  service: name={{ item }} enabled=no
  with_items:
    - libvirtd
    - libvirt-guests
  tags: [hypervisor, services]

- name: install cluster packages
  yum: name={{ item }} state=installed
  with_items:
    - ccs
    - cman
    - omping
    - rgmanager
  tags: [clusternode, packages]

- name: copy cluster_vm_on_fuse policy file
  copy: src=cluster_vm_on_fuse.pp dest=/opt/
  notify: install selinux policy
  tags: [clusternode, clusterpolicy]

- name: set ricci password
  user: name=ricci update_password=always password={{ ricci_password }}
  tags: [clusternode, ricci_password]

- name: cluster config
  template: src=cluster.conf dest=/etc/cluster/cluster.conf
  register: clusterconf
  tags: [clusternode, configs, clusterconfig]

- name: start and enable ricci service
  service: name={{ item }} state=started enabled=yes
  with_items:
    - ricci
    - modclusterd
    - cman
    - rgmanager
  register: start_cluster_services
  tags: [clusternode, services, clusterconfig]

- name: dummy task to conditionally trigger reload cluster handler
  shell: /bin/true
  when: clusterconf|changed and not start_cluster_services|changed
  notify: reload cluster config
  tags: clusterconfig

