---
- include: sshsetup.yml
- include: hostsfile.yml

- name: install cluster packages
  yum: name={{ item }} state=installed
  with_items:
    - ccs
    - cman
    - omping
    - rgmanager
  tags: [clusternode, packages]

- name: set ricci password
  user: name=ricci update_password=always password={{ ricci_password }}

- name: cluster config
  template: src=cluster.conf dest={{ root_prefix }}/etc/cluster/cluster.conf
  register: clusterconf
  tags: clusterconfig

#- name: start and enable ricci service
#  service: name={{ item }} state=started enabled=yes
#  with_items:
#    - ricci
#    - modclusterd
#    - cman
#    - rgmanager
#  tags: clusterservices

