---
- name: install hypervisor packages
  yum: name={{ item }} state=installed
  with_items:
    - qemu-kvm
    - libvirt
    - libvirt-client
    - libvirt-cim
    - libvirt-snmp
    - libvirt-python
    - perl-Sys-Virt
    - fence-virtd-libvirt
    - fence-virtd-multicast
    - fence-virtd-serial
    - libguestfs-tools
    - python-libguestfs
    - virt-top
    - python-virtinst
  tags: [hypervisor, packages]

- name: copy libvirt configs
  copy: src={{ item }} dest=/etc/libvirt/
  with_items:
    - libvirt.conf
    - libvirtd.conf
    - qemu.conf
  tags: [hypervisor, configs, hypervisorconfigs]
  notify: restart libvirtd

- name: start and enable hypervisor services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - libvirtd
    - libvirt-guests
  tags: [hypervisor, services]

- name: setup vnetworks port groups
  template: src=ifcfg/pg dest=/etc/sysconfig/network-scripts/ifcfg-pg{{ item['name'] }}
  with_items: vnetworks
  tags: [hypervisor, configs, vnetworks]

- name: setup vnetworks vlans
  template: src=ifcfg/vlan dest=/etc/sysconfig/network-scripts/ifcfg-{{ baseiface }}.{{ item['vlan'] }}
  with_items: vnetworks
  tags: [hypervisor, configs, vnetworks]

- name: start vnetworks port groups
  shell: ifup pg{{ item['name'] }}
  with_items: vnetworks
  ignore_errors: yes
  tags: [hypervisor, configs, vnetworks]

- name: start vnetworks vlans
  shell: ifup {{ baseiface }}.{{ item['vlan']}}
  with_items: vnetworks
  ignore_errors: yes
  tags: [hypervisor, configs, vnetworks]

- name: convenience scripts for /root/bin
  copy: src={{ item }} dest=/root/bin/ mode=0700
  with_items:
    - mig
  tags: [hypervisor, scripts]
