---
- name: install hypervisor packages
  yum: name={{ item }} state=installed
  with_items:
    - qemu-kvm
    - libvirt
    - libvirt-client
    - libvirt-cim
    - libvirt-snmp
    - libvirt-python
    - perl-Sys-Virt
    - fence-virtd-libvirt
    - fence-virtd-multicast
    - fence-virtd-serial
    - libguestfs-tools
    - python-libguestfs
    - virt-top
    - python-virtinst
  tags: [hypervisor, packages]

- include: iptables.yml

- name: tell selinux to allow nfs for virt
  seboolean: name=virt_use_nfs persistent=yes state=yes
  tags: [glusterfs, client, selinux]

- name: copy libvirt configs
  template: src=qemu.conf dest=/etc/libvirt/
  when: qemu_dynamic_ownsership is define
  tags: [hypervisor, configs, hypervisorconfigs]
  notify: restart libvirtd

- name: start and enable hypervisor services
  service: name={{ item }} state=started
  with_items:
    - libvirtd
    - libvirt-guests
  tags: [hypervisor, services]
  when: cluster_name is not defined

- name: start and enable hypervisor services
  service: name={{ item }} enabled=yes
  with_items:
    - libvirtd
    - libvirt-guests
  tags: [hypervisor, services]
  when: cluster_name is not defined

- name: setup vnetworks port groups
  template: src=ifcfg/pg dest=/etc/sysconfig/network-scripts/ifcfg-pg{{ item['name'] }}
  with_items: vnetworks
  tags: [hypervisor, configs, vnetworks]

- name: setup vnetworks vlans
  template: src=ifcfg/vlan dest=/etc/sysconfig/network-scripts/ifcfg-{{ baseiface }}.{{ item['vlan'] }}
  with_items: vnetworks
  tags: [hypervisor, configs, vnetworks]

- name: start vnetworks port groups
  shell: ifup pg{{ item['name'] }}
  with_items: vnetworks
  ignore_errors: yes
  changed_when: False
  tags: [hypervisor, configs, vnetworks]

- name: start vnetworks vlans
  shell: ifup {{ baseiface }}.{{ item['vlan']}}
  with_items: vnetworks
  ignore_errors: yes
  changed_when: False
  tags: [hypervisor, configs, vnetworks]

- name: convenience scripts for /root/bin
  copy: src={{ item }} dest=/root/bin/ mode=0700
  with_items:
    - mig
    - poolfixperms
    - savevmdef
  tags: [hypervisor, scripts]
