---
- name: add glusterfs repo
  copy: src=glusterfs-epel.repo dest=/etc/yum.repos.d/
  tags: [glusterfs, client, repos]

- name: add GPG key for glusterfs repo
  copy: src=glusterfs.key dest=/etc/pki/rpm-gpg/
  tags: [glusterfs, client, repos]

- name: install glusterfs client packages
  yum: name={{ item }} state=installed
  with_items:
    - glusterfs-fuse
  tags: [glusterfs, client, packages]

- name: tell selinux to allow fuse for virt
  sebool: name=virt_use_fusefs persistent=yes state=yes
  tags: [glusterfs, client, selinux]
