---
- name: ansible dependencies
  yum: name={{ item }} state=installed
  with_items:
    - libselinux-python
    - libsemanage-python
    - policycoreutils-python
  tags: [base, packages, ansibledeps]

- name: add epel repo
  action: copy src={{ item }} dest=/etc/yum.repos.d/
  with_items:
    - epel.repo
  tags: [base, repos]

- name: add gpg key for epel
  action: copy src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg/
  tags: [base, repos]

- name: install admin tools
  yum: name={{ item }} state=installed
  with_items:
    - vim-enhanced
    - iptraf
    - tcpdump
    - iperf
    - iftop
    - lsof
    - iotop
    - nmap
    - vconfig
    - git
    - screen
    - pykickstart
    - wget
    - telnet
    - ntp
    - tree
    - ebtables
    - ethtool
    - xfsprogs
    - ssmtp
    - lshw
    - ntp
    - sipcalc
    - setroubleshoot
  tags: [base, packages]

- name: ssmtp config
  template: src=ssmtp.conf dest=/etc/ssmtp/
  tags: [base, configs]

- name: setup ntp servers
  template: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntpd
  tags: [base, configs]

- name: start and enable services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - iptables
    - ip6tables
    - ebtables
    - ntpd
  tags: [base, services]

- name: update firewall configuration
  template: src=iptables dest=/etc/sysconfig/iptables
  tags: [base, configs, firewall]
  notify: reload firewall

- name: sysctl settings
  template: src=sysctl.conf dest=/etc/sysctl.conf
  tags: [base, configs, sysctl]
  notify: reload sysctl

- name: create root user bin directory
  file: name=/root/bin state=directory
  tags: [base, directories]
