---
- name: restart ntpd
  service: name=ntpd state=restarted

- name: compose iptables
  shell: cat /opt/rolefrags/iptables/* > /opt/rolefrags/iptables.compose

- name: reload firewall
  service: name=iptables state=reloaded

- name: reload sysctl
  command: sysctl -p
  ignore_errors: True
